name: meal_log
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_gallery_saver_plus: ^4.0.1
  device_info_plus: ^10.1.0
  image: ^4.1.7
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/meal_log.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true